apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-deploy
  labels:
    app: aks-deploy
  namespace: namespace-workflow-1702408057720
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-deploy
  template:
    metadata:
      labels:
        app: aks-deploy
    spec:
      containers:
        - name: aks-deploy
          image: acrworkflow1702408057720.azurecr.io/image-workflow-1702408057720:latest
          ports:
            - containerPort: 3000