apiVersion: v1
kind: Service
metadata:
  name: aks-deploy
  namespace: namespace-workflow-1702408057720
spec:
  type: LoadBalancer
  selector:
    app: aks-deploy
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000