apiVersion: v1
kind: Service
metadata:
  name: aks-deployment
  namespace: namespace-workflow-1702397773127
spec:
  type: LoadBalancer
  selector:
    app: aks-deployment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000