apiVersion: v1
kind: Service
metadata:
  name: myaks
  namespace: namespace-workflow-1702402943911
spec:
  type: LoadBalancer
  selector:
    app: myaks
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000